name: CMake Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake g++ build-essential libcriterion-dev \
            libx11-dev libxrandr-dev libudev-dev \
            libxcursor-dev libxi-dev libxinerama-dev \
            libopengl-dev libflac-dev libogg-dev \
            libvorbis-dev libopenal-dev libfreetype-dev

      - name: Cache SFML 3
        id: cache-sfml
        uses: actions/cache@v4
        with:
          path: ./sfml-install
          key: ${{ runner.os }}-sfml3-v1

      - name: Install SFML 3
        if: steps.cache-sfml.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch 3.0.0 https://github.com/SFML/SFML.git
          cmake -S SFML -B SFML/build \
            -DCMAKE_INSTALL_PREFIX=./sfml-install \
            -DSFML_BUILD_EXAMPLES=OFF \
            -DSFML_BUILD_TEST_SUITE=OFF \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build SFML/build --target install

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTS=ON \
            -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/sfml-install

      - name: Build Project
        run: cmake --build build --config Debug --target unittests arcade

      - name: Run Tests
        working-directory: build
        run: ctest --output-on-failure